// const obj = {
// label: "Абдурахман Джами", value="",
// label: "Айни", value="",
// label: "Ашт", value="",
// label: "Бабаджан Гафуров", value="",
// label: "Балджуван", value="",
// label: "Бохтар", value="",
// label: "Бустон", value="",
// label: "Вандж", value="",
// label: "Варзоб", value="",
// label: "Вахдат", value="",
// label: "Вахш", value="",
// label: "ВМКБ", value="",
// label: "Восе", value="",
// label: "Гисар", value="",
// label: "Горный-Матча", value="",
// label: "Гулистон", value="",
// label: "Дангара", value="",
// label: "Дарваз", value="",
// label: "Деваштич", value="",
// label: "Джаббар-Расулов", value="",
// label: "Джайхун", value="",
// label: "Джалолиддин Балхи", value="",
// label: "Дусти", value="",
// label: "Душанбе", value="",
// label: "Зафаробод", value="",
// label: "И. Сомони", value="",
// label: "Истаравшан", value="",
// label: "Истиклол", value="",
// label: "Исфара", value="",
// label: "Ишкошим", value="",
// label: "Канибадам", value="",
// label: "Кубодиён", value="",
// label: "Кулоб", value="",
// label: "Кушониён", value="",
// label: "Лахш", value="",
// label: "Левакант", value="",
// label: "Мастчоҳ", value="",
// label: "Муминабад", value="",
// label: "Мургаб", value="",
// label: "Норак", value="",
// label: "Носир Хусрав", value="",
// label: "Нурабад", value="",
// label: "Пенджикент", value="",
// label: "Пяндж", value="",
// label: "Рашт", value="",
// label: "Рогун", value="",
// label: "Рошткала", value="",
// label: "РРП", value="",
// label: "Рудаки", value="",
// label: "Рушан", value="",
// label: "Сангвор", value="",
// label: "Сино", value="",
// label: "Согд", value="",
// label: "Спитамен", value="",
// label: "Таджикабад", value="",
// label: "Темурмалик", value="",
// label: "Турсунзаде", value="",
// label: "Файзабад", value="",
// label: "Фархор", value="",
// label: "Фирдавси", value="",
// label: "Хамадони", value="",
// label: "Хатлон", value="",
// label: "Ховалинг", value="",
// label: "Хорог", value="",
// label: "Худжанд", value="",
// label: "Хуросон", value="",
// label: "Шамсиддин Шохин", value="",
// label: "Шахринав", value="",
// label: "Шахристан", value="",
// label: "Шахритус", value="",
// label: "Шохмансур", value="",
// label: "Шугнан", value="",
// label: "Яван", value="",
const obj = [
  { label: "Абдурахман Джами", value: "Abdurahman Jam" },
  { label: "Айни", value: "Ayni" },
  { label: "Ашт", value: "Asht" },
  { label: "Бабаджан Гафуров", value: "Babadjhan Gafurov" },
  { label: "Балджуван", value: "Baldjuvan" },
  { label: "Бохтар", value: "Bokhtar" },
  { label: "Бустон", value: "Buston" },
  { label: "Вандж", value: "Vandzh" },
  { label: "Варзоб", value: "Varzob" },
  { label: "Вахдат", value: "Vakhdat" },
  { label: "Вахш", value: "Vakhsh" },
  { label: "ВМКБ", value: "VMKB" },
  { label: "Восе", value: "Vose" },
  { label: "Гисар", value: "Gisar" },
  { label: "Горный-Матча", value: "Gorny-Matcha" },
  { label: "Гулистон", value: "Gulistoni" },
  { label: "Дангара", value: "Dangara" },
  { label: "Дарваз", value: "Darvaz" },
  { label: "Деваштич", value: "Devashich" },
  { label: "Джаббар-Расулов", value: "Jabbar-Rasulov" },
  { label: "Джайхун", value: "Jaihun" },
  { label: "Джалолиддин Балхи", value: "Jaloliddin Balkhi" },
  { label: "Дусти", value: "Dusti" },
  { label: "Душанбе", value: "Dushanbe" },
  { label: "Зафаробод", value: "Zafarabad" },
  { label: "И. Сомони", value: "I. Somoni" },
  { label: "Истаравшан", value: "Istaravshan" },
  { label: "Истиклол", value: "Istiklol" },
  { label: "Исфара", value: "Isfara" },
  { label: "Ишкошим", value: "Ishkoshim" },
  { label: "Канибадам", value: "Kanibadam" },
  { label: "Кубодиён", value: "Kubodiyon" },
  { label: "Кулоб", value: "Kulob" },
  { label: "Кушониён", value: "Kushoniyon" },
  { label: "Лахш", value: "Lakhsh" },
  { label: "Левакант", value: "Levokant" },
  { label: "Мастчоҳ", value: "Mastchoh" },
  { label: "Муминабад", value: "Muminabad" },
  { label: "Мургаб", value: "Murgab" },
  { label: "Норак", value: "Norak" },
  { label: "Носир Хусрав", value: "Nosir Khusrav" },
  { label: "Нурабад", value: "Nurabad" },
  { label: "Пенджикент", value: "Penjikent" },
  { label: "Пяндж", value: "Pyandzh" },
  { label: "Рашт", value: "Rasht" },
  { label: "Рогун", value: "Rogun" },
  { label: "Рошткала", value: "Roshtkala" },
  { label: "РРП", value: "RRP" },
  { label: "Рудаки", value: "Rudaki" },
  { label: "Рушан", value: "Rushan" },
  { label: "Сангвор", value: "Sangvor" },
  { label: "Сино", value: "Sino" },
  { label: "Согд", value: "Sogd" },
  { label: "Спитамен", value: "Spitamen" },
  { label: "Таджикабад", value: "Tajikabad" },
  { label: "Темурмалик", value: "Temurmalik" },
  { label: "Турсунзаде", value: "Tursunzade" },
  { label: "Файзабад", value: "Faizabad" },
  { label: "Фархор", value: "Farkhor" },
  { label: "Фирдавси", value: "Firdavsi" },
  { label: "Хамадони", value: "Khamadoni" },
  { label: "Хатлон", value: "Khatlon" },
  { label: "Ховалинг", value: "Khovaling" },
  { label: "Хорог", value: "Khorog" },
  { label: "Худжанд", value: "Khujand" },
  { label: "Хуросон", value: "Khurosan" },
  { label: "Шамсиддин Шохин", value: "Shamsiddin Shokhin" },
  { label: "Шахринав", value: "Shakhrinav" },
  { label: "Шахристан", value: "Shakhristan" },
  { label: "Шахритус", value: "Shakhrisabz" },
  { label: "Шохмансур", value: "Shokhmansur" },
  { label: "Шугнан", value: "Shugnan" },
  { label: "Яван", value: "Yavan" },
];
[
  {label: "Вазорат",value:"vazorat"}
]