import type { Metadata } from "next";
import React from "react";
// import { Inter } from "next/font/google";
import "./globals.css";
import HeaderKor from "./components/headerKor";

export const metadata: Metadata = {
  title: "KOR TJ - Портали ҷойҳои корӣ",
  description: "Generated by create next app",
};

import { Providers } from "./providers";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className="w-screen h-screen flex flex-col overflow-x-hidden">
        <HeaderKor />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
